### ISSUE TITLE
[ENHANCEMENT] - Support for Microsoft Windows?

### ISSUE THREAD

**Issue by flc995** [acwazz/fastapi-responseschema#2]
**Environment**
- `fastapi` version is: 0.79.0
- `fastapi-responseschema` version is: 1.2.2
- `python` version is: 3.9.12

**Describe the enhancement**
Hello, I'm a big fan of your work. I was just trying to run this library on a MS Windows environment in Conda. However I get the error:
`ModuleNotFoundError: No module named 'termios'`

There are some references that the module termios is only available on Linux:
https://stackoverflow.com/questions/52062977/unable-to-import-termios-package

By any chance do you expect to support Windows too? Maybe by using a cross-platform module, don't know. 
However I guess this is a low priority, just wanted to let you know.

**Expected behavior**
Work on Windows.

**Snippets**
Just used the example code in README.MD

**Additional context**
I'm a linux user usually, just happened to use Windows :(

![immagine](https://user-images.githubusercontent.com/2039832/183732738-f8e7a759-ed4d-4bb4-9b3d-c2c535594b37.png)

**Comment by acwazz** [comment]
Hello! Sorry for the delay, the problem was solved in version `1.3.0` there was an unused import causing the bug for non unix OS.
I removed the import in [this commit](https://github.com/acwazz/fastapi-responseschema/commit/a50472490bbb601f8d5ae5567d0de6108d925171#diff-f38ad8087c510b3eae3a34e6b60fbdd1095169d09690a7d35eb40453bd7567c7).

Thank you so much for your appreciation! :slightly_smiling_face:
